#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : iceauth
Version  : 1.0.7
Release  : 5
URL      : http://xorg.freedesktop.org/releases/individual/app/iceauth-1.0.7.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/app/iceauth-1.0.7.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: iceauth-bin
Requires: iceauth-doc
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
The iceauth program is used to edit and display the authorization
information used in connecting with ICE.   It operates very much
like the xauth program for X11 connection authentication records.

%package bin
Summary: bin components for the iceauth package.
Group: Binaries

%description bin
bin components for the iceauth package.


%package doc
Summary: doc components for the iceauth package.
Group: Documentation

%description doc
doc components for the iceauth package.


%prep
%setup -q -n iceauth-1.0.7

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/iceauth

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
